services:

  app:
    build: .
    container_name: pagalope_app

    working_dir: /app

    volumes:
      - .:/app

    ports:
      - "8000:8000"

    depends_on:
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest

    container_name: pagalope_sqlserver

    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Password123!"

    ports:
      - "1433:1433"

    volumes:
      - sqlserver_data:/var/opt/mssql

volumes:
  sqlserver_data:
